# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
services:
  - docker

language: R
cache: packages

before_install:
  - "docker pull ubuntu:16.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev gdal-bin

after_success:
  - Rscript -e 'covr::codecov()'
