# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
dist: bionic
sudo: required
warnings_are_errors: true

before_install:
  - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/bionic/latest'))" >> ~/.Rprofile.site
  - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
       paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
       ')'))" >> ~/.Rprofile.site

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
     - ccache
     - libprotobuf-dev
     - protobuf-compiler
     - libv8-dev
     - libjq-dev
     - libudunits2-dev
     - libproj-dev
     - libgeos-dev
     - libgdal-dev
     - libnetcdf-dev
     - netcdf-bin

after_success:
  - Rscript -e 'covr::codecov()'
